import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer';
import Header from '../components/Header';
import Ranking from '../components/Ranking';
import GameContent from '../components/GameContent';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Jab Typer Tech | Simple typing game with JavaScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <Header />
      <GameContent />
      <Ranking />
      <Footer />
    </>
  )
}

export default Home
